import React, { useState, useEffect } from "react";
import { LeftOutlined } from "@ant-design/icons";
import Processed from "./Processed";
import Processing from "./Processing";

const CreatePayment = () => {
	const [file, setFile] = useState("");
	const [processing, setProcessing] = useState(false);
	const [processed, setProcessed] = useState(false);

	useEffect(() => {
		console.log(file);
	}, [file, processing, processed]);

	return (
		<div className="bulk__payment-main">
			<span className="text-gray mb-2 mb-lg-3 d-inline-block">
				<LeftOutlined /> Back to Home
			</span>
			<h2 className="font-weight-bold mb-4">{!processed ? "Create Bulk Payment" : "Result"}</h2>
			{!processing ? (
				<div className="bg-white profile-details col-xl-8">
					<div className="d-flex h-100 align-items-stretch">
						<img className="bulk-img mr-3 rounded-circle" src="/assets/bulk-payment.png" alt="Bulk Payment" />
						<div className="d-flex flex-column justify-content-center align-items-between h-100">
							<h3>Bulk Payment</h3>
							<p className="text-gray mb-0">We automate payment for business transactions</p>
						</div>
					</div>

					<hr className="my-3" />

					<div className="row mb-4">
						<div className="col-md-6">
							<div className="form-group">
								<label htmlFor="bulk payment" className="text-gray font-weight-bold">
									Title of Bulk Payment
								</label>
								<input type="text" className="form-control w-100" name="bulk-payment" id="bulkPayment" />
							</div>
						</div>
						<div className="col-md-6">
							<div className="form-group">
								<label htmlFor="contacts to be paid" className="text-gray font-weight-bold">
									Total number of contacts to be paid
								</label>
								<input type="text" className="form-control w-100" name="bulk-payment" id="bulkPayment" />
							</div>
						</div>
					</div>

					<div>
						<label htmlFor="upload template" className="text-gray font-weight-bold">
							Upload your boardman payment template
						</label>
						<div className="input-group mb-3">
							<div className="input-group-prepend">
								<span className="input-group-text" id="basic-addon1">
									<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
										<mask id="mask0" mask-type="alpha" maskUnits="userSpaceOnUse" x="5" y="5" width="13" height="14">
											<path
												fillRule="evenodd"
												clipRule="evenodd"
												d="M16.9497 11.2929L11.5285 16.714C10.4867 17.7558 8.79911 17.7558 7.7573 16.714C6.7155 15.6722 6.7155 13.9846 7.7573 12.9428L13.6499 7.05024C14.3004 6.39971 15.3563 6.39971 16.0069 7.05024C16.6574 7.70078 16.6574 8.75673 16.0069 9.40727L11.0571 14.357C10.7979 14.6163 10.3736 14.6163 10.1143 14.357C9.85505 14.0977 9.85505 13.6735 10.1143 13.4142L14.5927 8.93586L13.8856 8.22876L9.40722 12.7071C8.75668 13.3576 8.75668 14.4136 9.40722 15.0641C10.0578 15.7147 11.1137 15.7147 11.7642 15.0641L16.714 10.1144C17.7558 9.07257 17.7558 7.38494 16.714 6.34314C15.6722 5.30133 13.9846 5.30133 12.9428 6.34314L7.0502 12.2357C5.61713 13.6688 5.61713 15.9881 7.0502 17.4211C8.48327 18.8542 10.8026 18.8542 12.2356 17.4211L17.6568 12L16.9497 11.2929Z"
												fill="white"
											/>
										</mask>
										<g mask="url(#mask0)">
											<rect
												x="12"
												y="-11.5702"
												width="33.3333"
												height="33.3333"
												transform="rotate(45 12 -11.5702)"
												fill="#0070FF"
											/>
											<mask
												id="mask1"
												mask-type="alpha"
												maskUnits="userSpaceOnUse"
												x="-12"
												y="-12"
												width="48"
												height="48"
											>
												<rect
													x="12"
													y="-11.5702"
													width="33.3333"
													height="33.3333"
													transform="rotate(45 12 -11.5702)"
													fill="white"
												/>
											</mask>
											<g mask="url(#mask1)"></g>
										</g>
									</svg>
								</span>
							</div>
							<input
								type="file"
								className="form-control"
								placeholder="Browse file or drag and drop files here"
								aria-label="file"
								onChange={(e) => setFile(e.target.value)}
							/>
						</div>
						{file ? (
							<p className="text-uppercase">
								<span className="text-dark-blue">2,000´</span> contacts found
							</p>
						) : (
							""
						)}
					</div>

					{!file ? (
						<div className="p-3 p-md-4 p-lg-5 my-5" style={{ background: "#f7fafc" }}>
							<h4 className="font-weight-bold">What's the Boardman Bulk Template?</h4>
							<p className="text-gray">
								It’s an autogenerated template for you to upload all the contacts you want to disburse funds to and the
								specific milestones you want attached.
							</p>
							<div>
								<button className="btn bg-transparent border rounded px-4 py-3">Download template here</button>
								<button className="btn bg-transparent text-underline px-4 py-3 text-dark-blue">View Samples here</button>
							</div>
						</div>
					) : (
						<button className="bg-success px-4 py-2 rounded btn text-light" onClick={() => setProcessing(true)}>
							<span className="font-weight-bold">Next:</span> <span>Process Bulk Payment</span>
						</button>
					)}
				</div>
			) : !processed ? (
				<Processing setProcessed={setProcessed} />
			) : (
                <Processed />
            )}
		</div>
	);
};

export default CreatePayment;
